// @generated
// This file is @generated by prost-build.
/// A fill the floor turned away.
///
/// This message exists because a refusal cannot be expressed as an event. SettledBelowFloor is a
/// revert; reverted transactions emit no logs at all, so nothing log-driven can see one. The
/// Firehose block model carries every transaction with its status and its call tree, which is the
/// only place these numbers exist.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Refusal {
    #[prost(string, tag="1")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub block_number: u64,
    #[prost(uint64, tag="3")]
    pub timestamp: u64,
    /// Decoded from the revert data of the failing call.
    #[prost(string, tag="4")]
    pub recipient: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub token_in: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub token_out: ::prost::alloc::string::String,
    /// Rate the fill would have settled at, and the floor it was measured against.
    /// Both in the canonical convention: received * 1e18 / given, as decimal strings.
    #[prost(string, tag="7")]
    pub execution_rate: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub floor_rate: ::prost::alloc::string::String,
    /// The router the call was made to.
    #[prost(string, tag="9")]
    pub router: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Refusals {
    #[prost(message, repeated, tag="1")]
    pub refusals: ::prost::alloc::vec::Vec<Refusal>,
}
// @@protoc_insertion_point(module)
