// GENERATED by scripts/gen-revert-selectors.mjs from the contracts. Do not edit by hand.
//
// Every custom error the router or the registry can revert with, keyed by its four-byte selector.
// Regenerate with `npm run gen:selectors`; `npm run check` fails if this file is stale.

export const REVERT_REASONS: Record<string, string> = {
  "0x20fa6b71": "AbsoluteRateTooLarge", // AbsoluteRateTooLarge(uint256)
  "0x8a64f273": "AmountAboveMandate", // AmountAboveMandate(address,uint256,uint256)
  "0x5760fd80": "BadGuardianSignature", // BadGuardianSignature(address,address,bytes32)
  "0x4a8d2c07": "BadMandateSignature", // BadMandateSignature()
  "0x488c6ada": "BadReferenceAnswer", // BadReferenceAnswer(address,address,int256)
  "0x714d2b93": "BadReferenceConfig", // BadReferenceConfig()
  "0x9a6976c3": "ConcentratedBookBadSpread", // ConcentratedBookBadSpread(uint256,uint16)
  "0x58dd8d9e": "ConcentratedBookEmptyRange", // ConcentratedBookEmptyRange(uint256,uint256)
  "0xab8b67c6": "LengthMismatch", // LengthMismatch(uint256,uint256)
  "0x71a3df95": "LoweringStillTimelocked", // LoweringStillTimelocked(uint64)
  "0xef15bd7b": "MandateExpired", // MandateExpired(uint256)
  "0x934e3ca1": "MandateWasRevoked", // MandateWasRevoked(uint256)
  "0xf22ee1e4": "MandateWrongApp", // MandateWrongApp(address,address)
  "0x1758c287": "MandateWrongDelegate", // MandateWrongDelegate(address,address)
  "0xa7cdef52": "MaxAdverseBpsOutOfRange", // MaxAdverseBpsOutOfRange(uint16)
  "0x7a36ad40": "NoGuardian", // NoGuardian()
  "0xb0dc091d": "NoGuardianRegistered", // NoGuardianRegistered(address)
  "0xcf41c3cd": "NoPendingLowering", // NoPendingLowering(address,address,address)
  "0xa6fba094": "NoReferenceFeed", // NoReferenceFeed(address,address)
  "0xcc4ea466": "NotARaise", // NotARaise(uint16,uint16,uint256,uint256)
  "0x8a7be9ec": "NotDelegate", // NotDelegate(address)
  "0x2914f355": "NotDockAuthorised", // NotDockAuthorised(address)
  "0xbf4ed8b6": "NotRevokeAuthorised", // NotRevokeAuthorised(address)
  "0x771946d9": "ReferenceAlreadySet", // ReferenceAlreadySet(address,address,address)
  "0x89051165": "RenounceDisabled", // RenounceDisabled()
  "0x027e4c46": "SettledBelowFloor", // SettledBelowFloor(address,address,address,uint256,uint256)
  "0xc4679dec": "SetupLengthMismatch", // SetupLengthMismatch()
  "0xcd21db4f": "SignatureExpired", // SignatureExpired(uint256)
  "0x50ee0156": "StaleReference", // StaleReference(address,address,uint256,uint256)
  "0xc7d0d7fb": "TokenOutsideMandate", // TokenOutsideMandate(address)
  "0xe86f59ea": "TooSoon", // TooSoon(uint256)
  "0xa3c996d3": "WrongNonce", // WrongNonce(uint256,uint256)
};
