[package]
name = "subfloor-substreams"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
substreams = "0.6"
substreams-ethereum = "0.10"
prost = "0.13"
prost-types = "0.13"
hex = "0.4"

[build-dependencies]
anyhow = "1"
substreams-ethereum = "0.10"

[profile.release]
lto = true
opt-level = "s"
strip = "debuginfo"
