// Generates src/opcodes.ts from the VM's own enum, so a renamed or newly claimed opcode cannot
// drift out of the decoder silently. Run it after any change to OpcodeList.sol.
//
//   node scripts/gen-opcodes.mjs
import { readFileSync, writeFileSync } from "node:fs";

const SRC = "../../../contracts/src/libs/OpcodeList.sol";
const OUT = "../src/opcodes.ts";

const src = readFileSync(new URL(SRC, import.meta.url), "utf8");
const body = src.slice(src.indexOf("enum Opcode {") + "enum Opcode {".length, src.lastIndexOf("}"));

const names = [];
for (const raw of body.split("\n")) {
  const line = raw.replace(/\/\*.*?\*\//g, "").trim();
  if (!line || line.startsWith("//")) continue;
  for (const name of line.split(",")) {
    const n = name.trim();
    if (n) names.push(n);
  }
}
if (names.length !== 256) throw new Error(`expected 256 opcodes, parsed ${names.length}`);

const rows = names.map((n, i) => (n.match(/^_[0-9a-f]{2}$/) ? "" : n));

writeFileSync(
  new URL(OUT, import.meta.url),
  `// GENERATED by scripts/gen-opcodes.mjs from contracts/src/libs/OpcodeList.sol. Do not edit.
//
// An unallocated slot is the empty string, which the decoder renders as \`UNKNOWN_0x..\` — a program
// using a slot this table does not know about is a fact worth showing, not one worth hiding.

export const OPCODE_NAMES: string[] = [
${rows.map((n) => `  "${n}",`).join("\n")}
];

export function opcodeName(opcode: i32): string {
  if (opcode < 0 || opcode > 255) return "INVALID";
  const n = OPCODE_NAMES[opcode];
  return n.length == 0 ? "UNKNOWN" : n;
}
`,
);
console.log(`wrote ${OUT}: ${rows.filter((r) => r).length} allocated of 256`);
