// SPDX-License-Identifier: LicenseRef-Degensoft-SwapVM-1.1
pragma solidity 0.8.30;

/// @custom:license-url https://github.com/1inch/swap-vm/blob/main/LICENSES/SwapVM-1.1.txt
/// @custom:copyright © 2026 Degensoft Ltd

library OpcodeOps {
    function asU8(Opcode opcode) internal pure returns (uint8) {
        return uint8(opcode);
    }
}

/// @notice Opcode space layout, banked by instruction family
/// @dev For new instructions take the next free `_Ix` slots of their family bank
/// @dev The reserved bank (0xf0-0xff) is never allocated
enum Opcode {
    // 0x00-0x0f | Core control flow: halt, revert, jumps, extensions
    /* 00 */ Stop,
    /* 01 */ Revert,
    /* 02 */ Salt,
    /* 03 */ Jump,
    /* 04 */ Extruction,
    /* 05 */ _05,
    /* 06 */ _06,
    /* 07 */ _07,
    /* 08 */ _08,
    /* 09 */ _09,
    /* 0a */ _0a,
    /* 0b */ _0b,
    /* 0c */ _0c,
    /* 0d */ _0d,
    /* 0e */ _0e,
    /* 0f */ _0f,

    // 0x10-0x1f | Debug: wired only into *Debug opcode sets
    /* 10 */ PrintSwapRegisters,
    /* 11 */ PrintSwapQuery,
    /* 12 */ PrintVM,
    /* 13 */ PrintFreeMemoryPointer,
    /* 14 */ PrintGasLeft,
    /* 15 */ PrintFee,
    /* 16 */ _16,
    /* 17 */ _17,
    /* 18 */ _18,
    /* 19 */ _19,
    /* 1a */ PatchSwapRegisters,
    /* 1b */ _1b,
    /* 1c */ _1c,
    /* 1d */ _1d,
    /* 1e */ _1e,
    /* 1f */ _1f,

    // 0x20-0x3f | Conditions & access guards: taker/time validation, whitelists, conditional jumps
    /* 20 */ Deadline,
    /* 21 */ _21,
    /* 22 */ _22,
    /* 23 */ OnlyTakerTokenBalanceNonZero,
    /* 24 */ OnlyTakerTokenBalanceGte,
    /* 25 */ OnlyTakerTokenSupplyShareGte,
    /* 26 */ OnlyTxOriginTokenBalanceNonZero,
    /* 27 */ _27,
    /* 28 */ _28,
    /* 29 */ _29,
    /* 2a */ _2a,
    /* 2b */ PrivateOrder,
    /* 2c */ WhitelistCoequal,
    /* 2d */ WhitelistSequential,
    /* 2e */ _2e,
    /* 2f */ _2f,
    /* 30 */ JumpIfDirection,
    /* 31 */ JumpIfTokenIn,
    /* 32 */ JumpIfTokenOut,
    /* 33 */ _33,
    /* 34 */ _34,
    /* 35 */ _35,
    /* 36 */ _36,
    /* 37 */ _37,
    /* 38 */ _38,
    /* 39 */ _39,
    /* 3a */ _3a,
    /* 3b */ _3b,
    /* 3c */ _3c,
    /* 3d */ _3d,
    /* 3e */ _3e,
    /* 3f */ _3f,

    // 0x40-0x4f | Invalidators & epochs: order/series invalidation
    /* 40 */ InvalidateBit,
    /* 41 */ InvalidateTokenIn,
    /* 42 */ InvalidateTokenOut,
    /* 43 */ _43,
    /* 44 */ _44,
    /* 45 */ _45,
    /* 46 */ _46,
    /* 47 */ _47,
    /* 48 */ ValidateSeriesEpoch,
    /* 49 */ _49,
    /* 4a */ _4a,
    /* 4b */ _4b,
    /* 4c */ _4c,
    /* 4d */ _4d,
    /* 4e */ _4e,
    /* 4f */ _4f,

    // 0x50-0x6f | Swap curves: instructions computing swap amounts from balances
    /* 50 */ XYCSwap,
    /* 51 */ XYCConcentrateSwap,
    /* 52 */ _52,
    /* 53 */ LimitSwap,
    /* 54 */ LimitSwapFullAmount,
    /* 55 */ _55,
    /* 56 */ _56,
    /* 57 */ _57,
    /* 58 */ PeggedSwap,
    /* 59 */ _59,
    /* 5a */ _5a,
    /* 5b */ _5b,
    /* 5c */ _5c,
    /* 5d */ _5d,
    /* 5e */ _5e,
    /* 5f */ _5f,
    /* 60 */ _60,
    /* 61 */ _61,
    /* 62 */ _62,
    /* 63 */ _63,
    /* 64 */ _64,
    /* 65 */ _65,
    /* 66 */ _66,
    /* 67 */ _67,
    /* 68 */ _68,
    /* 69 */ _69,
    /* 6a */ _6a,
    /* 6b */ _6b,
    /* 6c */ _6c,
    /* 6d */ _6d,
    /* 6e */ _6e,
    /* 6f */ _6f,

    // 0x70-0x8f | Fees
    /* 70 */ FeeFlatIn,
    /* 71 */ FeeFlatOut,
    /* 72 */ _72,
    /* 73 */ _73,
    /* 74 */ _74,
    /* 75 */ _75,
    /* 76 */ _76,
    /* 77 */ _77,
    /* 78 */ _78,
    /* 79 */ _79,
    /* 7a */ _7a,
    /* 7b */ _7b,
    /* 7c */ _7c,
    /* 7d */ _7d,
    /* 7e */ _7e,
    /* 7f */ _7f,
    /* 80 */ FeeProtocol,
    /* 81 */ _81,
    /* 82 */ _82,
    /* 83 */ _83,
    /* 84 */ _84,
    /* 85 */ _85,
    /* 86 */ _86,
    /* 87 */ _87,
    /* 88 */ _88,
    /* 89 */ _89,
    /* 8a */ _8a,
    /* 8b */ _8b,
    /* 8c */ _8c,
    /* 8d */ _8d,
    /* 8e */ _8e,
    /* 8f */ _8f,

    // 0x90-0xaf | Balances tuning: setting and adjustment of virtual balances
    /* 90 */ StaticBalances,
    /* 91 */ DynamicBalances,
    /* 92 */ _92,
    /* 93 */ _93,
    /* 94 */ DutchAuctionBalanceIn,
    /* 95 */ DutchAuctionBalanceOut,
    /* 96 */ _96,
    /* 97 */ _97,
    /* 98 */ PiecewiseLinearScaleBalanceIn,
    /* 99 */ PiecewiseLinearScaleBalanceOut,
    /* 9a */ _9a,
    /* 9b */ _9b,
    /* 9c */ Decay,
    /* 9d */ TWAPSwap,
    /* 9e */ _9e,
    /* 9f */ _9f,
    /* a0 */ _a0,
    /* a1 */ _a1,
    /* a2 */ _a2,
    /* a3 */ _a3,
    /* a4 */ _a4,
    /* a5 */ _a5,
    /* a6 */ _a6,
    /* a7 */ _a7,
    /* a8 */ _a8,
    /* a9 */ _a9,
    /* aa */ _aa,
    /* ab */ _ab,
    /* ac */ _ac,
    /* ad */ _ad,
    /* ae */ _ae,
    /* af */ _af,

    // 0xb0-0xcf | Rates tuning: exchange-rate constraints and price adjustment
    /* b0 */ RequireMinRate,
    /* b1 */ AdjustMinRate,
    /* b2 */ OraclePriceAdjuster,
    /* b3 */ _b3,
    /* b4 */ BaseFeeAdjuster,
    /* b5 */ _b5,
    /* b6 */ _b6,
    /* b7 */ _b7,
    /* b8 */ _b8,
    /* b9 */ _b9,
    /* ba */ _ba,
    /* bb */ _bb,
    /* bc */ _bc,
    /* bd */ _bd,
    /* be */ _be,
    /* bf */ _bf,
    /* c0 */ _c0,
    /* c1 */ _c1,
    /* c2 */ _c2,
    /* c3 */ _c3,
    /* c4 */ _c4,
    /* c5 */ _c5,
    /* c6 */ _c6,
    /* c7 */ _c7,
    /* c8 */ _c8,
    /* c9 */ _c9,
    /* ca */ _ca,
    /* cb */ _cb,
    /* cc */ _cc,
    /* cd */ _cd,
    /* ce */ _ce,
    /* cf */ _cf,

    // 0xd0-0xef | Unallocated
    /* d0 */ _d0,
    /* d1 */ _d1,
    /* d2 */ _d2,
    /* d3 */ _d3,
    /* d4 */ _d4,
    /* d5 */ _d5,
    /* d6 */ _d6,
    /* d7 */ _d7,
    /* d8 */ _d8,
    /* d9 */ _d9,
    /* da */ _da,
    /* db */ _db,
    /* dc */ _dc,
    /* dd */ _dd,
    /* de */ _de,
    /* df */ _df,
    /* e0 */ _e0,
    /* e1 */ _e1,
    /* e2 */ _e2,
    /* e3 */ _e3,
    /* e4 */ _e4,
    /* e5 */ _e5,
    /* e6 */ _e6,
    /* e7 */ _e7,
    /* e8 */ _e8,
    /* e9 */ _e9,
    /* ea */ _ea,
    /* eb */ _eb,
    /* ec */ _ec,
    /* ed */ _ed,
    /* ee */ _ee,
    /* ef */ _ef,

    // 0xf0-0xff | Reserved: never allocate (potential 2-byte opcode escape-prefix)
    /* f0 */ _f0,
    /* f1 */ _f1,
    /* f2 */ _f2,
    /* f3 */ _f3,
    /* f4 */ _f4,
    /* f5 */ _f5,
    /* f6 */ _f6,
    /* f7 */ _f7,
    /* f8 */ _f8,
    /* f9 */ _f9,
    /* fa */ _fa,
    /* fb */ _fb,
    /* fc */ _fc,
    /* fd */ _fd,
    /* fe */ _fe,
    /* ff */ _ff
}
