[profile.default]
solc_version   = "0.8.30"
optimizer      = true
optimizer_runs = 700
via_ir         = true
fs_permissions = [
    { access = "read-write", path = "./deployments" },
    { access = "read-write", path = "./config" }
]

[fmt]
single_line_statement_blocks = "multi"
multiline_func_header        = "all"
override_spacing             = false
bracket_spacing              = true
int_types                    = "long"
number_underscore            = "thousands"

[profile.ci]
solc_version   = "0.8.30"
optimizer      = true
optimizer_runs = 700
via_ir         = true
